### PR TITLE
Fix optional performer and non-optional period

### LINKED ISSUE #9: missing performer in api call gives panic
open api spec says performer is optional

### PR DESCRIPTION
**Pull request by stevenvegt**
Fix #9

### CODE REVIEW

File: pkg/consent-logic_test.go [hunk 1]
```diff
@@ -589,3 +589,43 @@ func Test_hashFHIRConsent(t *testing.T) {
...
+
+	createConsentRequest := &CreateConsentRequest{
+		Custodian: IdentifierURI(custodianAGB),
+		Subject:   "bsn:1234",
+		Actor:     IdentifierURI(actorAGB),
+		Records:   []Record{{}},
+	}
+	consentLogic := &ConsentLogic{NutsRegistry: registryMock, NutsCrypto: cryptoMock}
+	event, err := consentLogic.buildConsentRequestConstructedEvent(createConsentRequest)
+	if err != nil {
```
Comment (woutslakhorst) [inline pkg/consent-logic_test.go]: It would be a good moment to introduce testify assertions
